language: cpp

compiler:
    - clang

install:
# Install C++11-compatible clang-3.4 from pre-built repository
    - sudo add-apt-repository -y ppa:h-rayflood/llvm
    - sudo apt-get update -qq
    - sudo apt-get install gcov
    - sudo apt-get install --allow-unauthenticated -qq clang-3.4
# Build and install libc++
    - export CXXFLAGS="-std=c++0x -stdlib=libc++"
    - svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk libcxx
    - cd libcxx/lib && bash buildit
    - sudo cp ./libc++.so.1.0 /usr/lib/
    - sudo mkdir /usr/include/c++/v1
    - cd .. && sudo cp -r include/* /usr/include/c++/v1/
    - cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so
    - sudo ln -sf libc++.so.1.0 libc++.so.1 && cd $cwd
    - sudo ldconfig
    - ldconfig -p
# Build and install libc++abi
    - svn co http://llvm.org/svn/llvm-project/libcxxabi/trunk libcxxabi
    - cd libcxxabi/lib
    - ./buildit
    - sudo cp libc++abi.so.1.0 /usr/lib
    - sudo ln -s /usr/lib/libc++abi.so.1.0 /usr/lib/libc++abi.so.1
    - sudo ln -s /usr/lib/libc++abi.so.1 /usr/lib/libc++abi.so
    - cd .. && sudo cp -r include/* /usr/include/c++/v1/
    - export CXX="clang++-3.4"

script:
    - cd $TRAVIS_BUILD_DIR
    - export CXXFLAGS="-std=c++11 -stdlib=libc++ -lc++abi"
    - cmake . && make

after_success:
    - ./algorithmscpp   # Run unit tests
    - make coveralls    # Send coverage to Coveralls

branches:
    only:
        - master

