language: cpp

compiler: clang

notifications:
  email: false

before_install: # Prepare system
# Update cmake
    - cd
    - wget http://www.cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.tar.gz
    - sudo mkdir /usr/local/opt
    - cd /usr/local/opt
    - sudo tar -zxvf ~/cmake-3.2.1-Linux-x86_64.tar.gz
    - export PATH="/usr/local/opt/cmake-3.2.1-Linux-x86_64/bin:$PATH"
# Install C++11-compatible clang-3.6
    - sudo add-apt-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main'
    - sudo add-apt-repository 'deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main'
    - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
    - sudo apt-get update -qq
    - sudo apt-get install clang-3.6 libclang-common-3.6-dev libclang-3.6-dev libclang1-3.6 libllvm-3.6-ocaml-dev libllvm3.6 lldb-3.6 llvm-3.6 llvm-3.6-dev llvm-3.6-runtime lldb-3.6-dev
# Coveralls Code Coverage
    - sudo pip install cpp-coveralls
# Build and install libc++
    - cd
    - export CXXFLAGS="-std=c++0x -stdlib=libc++"
    - svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk libcxx
    - cd libcxx/lib && bash buildit
    - sudo cp ./libc++.so.1.0 /usr/lib/
    - sudo mkdir /usr/include/c++/v1
    - cd .. && sudo cp -r include/* /usr/include/c++/v1/
    - cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so
    - sudo ln -sf libc++.so.1.0 libc++.so.1 && cd $cwd
    - sudo ldconfig
# Build and install libc++abi
    - svn co http://llvm.org/svn/llvm-project/libcxxabi/trunk libcxxabi
    - cd libcxxabi/lib
    - ./buildit
    - sudo cp libc++abi.so.1.0 /usr/lib
    - sudo ln -s /usr/lib/libc++abi.so.1.0 /usr/lib/libc++abi.so.1
    - sudo ln -s /usr/lib/libc++abi.so.1 /usr/lib/libc++abi.so
    - cd .. && sudo cp -r include/* /usr/include/c++/v1/
    - export CXX="clang++-3.6"
# biicode package manager
    - cd && wget http://apt.biicode.com/install.sh && chmod +x install.sh && ./install.sh
# flawfinder C++ linter
    - sudo apt-get install flawfinder

install: # Build
    - cd $TRAVIS_BUILD_DIR
    - bii init -L
    - export CXXFLAGS="-std=c++14 -stdlib=libc++"
    - export LDFLAGS="$LDFLAGS -lLLVMCore -lLLVMSupport $(llvm-config-3.6 --ldflags)"
    - build_and_test() { bii clean; bii build -- VERBOSE=1; ./bin/algorithmscpp; }
# Undefined and Address Sanitizers
    - export SAN="UA"
    - export ASAN_OPTIONS="detect_leaks=1" # Enable leak sanitizer
    - build_and_test
    - ./lint_and_analyze.sh
# Memory Sanitizer: Temporarily disabled because it's difficult to build the standard libraries with -fsanitize=memory
    #- export SAN="M"
    #- build_and_test
# Thread Sanitizer
    - export SAN="T"
    - export COVERAGE=true
    - build_and_test

script:
    - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then coveralls -t 6EbYFzTh2DqoPYIqEOwchkuWCs6Nyr2cK -i $TRAVIS_BUILD_DIR/src/ -r $TRAVIS_BUILD_DIR --gcov-options '\-lp'; fi

branches:
    only:
        - master

# Coverity Scan
env:
  global:
   - secure: "hKt8ooWMkekrEhd++Opo+yjyfTyNLYrwDQM+FsinE5QNIiJ5pakUnwtDf6wgDlqImJRklctxRkrHI4lSQnS483aaemcCHjH/1wxvrE3SlGza8oFZS/yQ1tj6P1J9u5WmaB9fVEvxTLAa3by8d1bUTgaGjZrt4WemOV1Qz6MtGo4="

addons:
  coverity_scan:
    project:
      name: "alexdunn/aalgocpp"
      description: "Build submitted via Travis CI"
    notification_email: worthless.trash.junk@icloud.com
    build_command_prepend: "bii configure"
    build_command:   "CXX=clang++-3.6 CXXFLAGS=\"-std=c++14 -stdlib=libc++\" bii build"
    branch_pattern: coverity_scan

