language: cpp

compiler: clang

notifications:
  email: false

before_install: # Prepare system
# Update cmake
    - cd
    - wget http://www.cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.tar.gz
    - sudo mkdir /usr/local/opt
    - cd /usr/local/opt
    - sudo tar -zxvf cmake-3.2.1-Linux-x86_64.tar.gz
    - export PATH="/usr/local/opt/cmake-3.2.1-Linux-x86_64/bin"
# Install C++11-compatible clang-3.6
    - sudo add-apt-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main'
    - sudo add-apt-repository 'deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main'
    - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
    - sudo apt-get update -qq
    - sudo apt-get install clang-3.6 libclang-common-3.6-dev libclang-3.6-dev libclang1-3.6 libclang1-3.6-dbg libllvm3.6 libllvm3.6-dbg lldb-3.6 llvm-3.6 llvm-3.6-dev llvm-3.6-runtime
# Coveralls Code Coverage
    - sudo pip install cpp-coveralls
# Build and install libc++
    - export CXXFLAGS="-std=c++0x -stdlib=libc++"
    - svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk libcxx
    - cd libcxx/lib && bash buildit
    - sudo cp ./libc++.so.1.0 /usr/lib/
    - sudo mkdir /usr/include/c++/v1
    - cd .. && sudo cp -r include/* /usr/include/c++/v1/
    - cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so
    - sudo ln -sf libc++.so.1.0 libc++.so.1 && cd $cwd
    - sudo ldconfig
# Build and install libc++abi
    - svn co http://llvm.org/svn/llvm-project/libcxxabi/trunk libcxxabi
    - cd libcxxabi/lib
    - ./buildit
    - sudo cp libc++abi.so.1.0 /usr/lib
    - sudo ln -s /usr/lib/libc++abi.so.1.0 /usr/lib/libc++abi.so.1
    - sudo ln -s /usr/lib/libc++abi.so.1 /usr/lib/libc++abi.so
    - cd .. && sudo cp -r include/* /usr/include/c++/v1/
    - export CXX="clang++-3.6"
# biicode package manager
    - cd && wget http://apt.biicode.com/install.sh && chmod +x install.sh && ./install.sh

install: # Build
    - cd $TRAVIS_BUILD_DIR
    - bii init -L
# Address Sanitizer
    - export SAN="A"
    - bii build
    - ./bin/algorithmscpp
# Memory Sanitizer
    - export SAN="M"
    - bii build
    - ./bin/algorithmscpp
# Thread Sanitizer
    - export SAN="T"
    - bii build
    - ./bin/algorithmscpp

script:
    - coveralls -t LCXV38Owi5bu4dMU00rn5eWzoEPYXyupF -i $TRAVIS_BUILD_DIR/src/ -r $TRAVIS_BUILD_DIR --gcov-options '\-lp'

branches:
    only:
        - master

